### ISSUE TITLE
auto reconnecting

### ISSUE THREAD

**Issue by chemod** [jefrisibarani/tobasaqueue#1]
malam mas jefri.... antriannya kalo servernya dc dia hrs kita restart dulu... mungkin perlu ditambahkan auto reconnecting ke server(service) jika servernya kita restart.. jadi display dan caller bisa otomatis koneksi.. thx

**Comment by jefrisibarani** [comment]
Ok om chemod, itu masuk ke PR ya. 
Terimakasih infonya
